export const ALCOHOL_UPGRADES_LIST = [
  { id: 'moet_rose', name: 'Moët & Chandon Rosé Impérial Champagne', defaultPriceUSD: 140 },
  { id: 'moet_brut', name: 'Moët & Chandon Brut Impérial Champagne', defaultPriceUSD: 120 },
  { id: 'veuve_rose', name: 'Veuve Clicquot Ponsardin Rosé Champagne', defaultPriceUSD: 170 },
  { id: 'veuve_brut', name: 'Veuve Clicquot Ponsardin Brut Champagne', defaultPriceUSD: 130 },
  { id: 'prosecco', name: 'Sparkling wine Prosecco', defaultPriceUSD: 40 },
  { id: 'sparkling_rose', name: 'Sparkling wine Rosé', defaultPriceUSD: 30 },
  { id: 'buchanans_12', name: 'Buchanans 12 years old Whiskey', defaultPriceUSD: 60 },
  { id: 'jw_black', name: 'Johnnie Walker Black Label Whiskey', defaultPriceUSD: 90 },
  { id: 'chivas_12', name: 'Chivas Regal 12 years Whiskey', defaultPriceUSD: 60 },
  { id: 'crown_royal', name: 'Crown Royal Whiskey', defaultPriceUSD: 70 },
  { id: 'hennessy_vs', name: 'Hennessy Very Special', defaultPriceUSD: 90 },
  { id: 'titos', name: 'Tito’s Vodka', defaultPriceUSD: 60 },
  { id: 'grey_goose', name: 'Grey Goose Vodka', defaultPriceUSD: 90 },
  { id: 'ketel_one', name: 'Ketel One Vodka', defaultPriceUSD: 40 },
  { id: 'absolut', name: 'Absolut Vodka', defaultPriceUSD: 30 },
  { id: 'ciroc', name: 'Ciroc Vodka', defaultPriceUSD: 70 },
  { id: 'hendricks', name: 'Hendrick’s Gin', defaultPriceUSD: 100 },
  { id: 'bombay', name: 'Bombay Sapphire Gin', defaultPriceUSD: 50 },
  { id: 'havana_seleccion', name: 'Havana Club Selección Rum', defaultPriceUSD: 90 },
  { id: 'havana_7', name: 'Havana Club 7-year-old Rum', defaultPriceUSD: 50 },
  { id: 'don_julio_repo', name: 'Don Julio Reposado Tequila', defaultPriceUSD: 90 },
  { id: 'don_julio_blanco', name: 'Don Julio Blanco Tequila', defaultPriceUSD: 60 },
  { id: 'don_julio_1942', name: 'Don Julio 1942 Añejo', defaultPriceUSD: 330 },
  { id: 'clase_azul', name: 'Clase Azul Reposado', defaultPriceUSD: 280 },
  { id: 'cava_de_oro', name: 'Cava de Oro', defaultPriceUSD: 50 },
  { id: 'casamigos_repo', name: 'Tequila Casamigos Reposado', defaultPriceUSD: 70 },
  { id: 'patron_anejo', name: 'Patrón Añejo Tequila', defaultPriceUSD: 90 },
  { id: 'patron_silver', name: 'Patrón Silver Tequila', defaultPriceUSD: 60 },
  { id: 'mezcal_alberto', name: 'Mezcal Artesanal Reserva de Don Alberto', defaultPriceUSD: 50 },
  { id: 'casa_madero_3v', name: 'Casa Madero 3V red Wine', defaultPriceUSD: 50 },
  { id: 'casa_madero_white', name: 'Casa Madero white Wine', defaultPriceUSD: 50 },
  { id: 'red_bull_4', name: 'Red Bull pack of 4 Cans', defaultPriceUSD: 20 },
  { id: 'hard_seltzer_6', name: 'Hard seltzer 6 pack (lime, mango, grapefruit, berries)', defaultPriceUSD: 10 },
];